name: ml_practice
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_image_labeling: ^0.10.0
  google_mlkit_text_recognition: ^0.11.0
  crypto: ^3.0.3
  syncfusion_flutter_pdf: ^24.2.8
  file_picker: ^6.1.1
  image: ^4.1.7
  pie_chart: ^5.4.0
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  pdf: ^3.11.3
  excel: ^4.0.2
  path_provider: ^2.1.5
  cross_file: ^0.3.4+1
  share_plus: ^10.1.4
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  open_file: ^3.3.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.2
  http: ^1.4.0
  http_parser: ^4.0.2
  audioplayers: ^6.4.0
  provider: ^6.1.2

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  # web:
  #   generate: true
  image_path_android: 'assets/svgs/Icon_f.png'
  image_path_ios: 'assets/svgs/Icon_f.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/svgs/Icon_f.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
